### ISSUE TITLE
stergere produse admin eroare

### ISSUE THREAD

**Issue by cozmoximo** [opencartromania/oc-1.5.6.4-stable#1]
ramasa linia asta in controller/catalog/product.php
            $this->openbay->deleteProduct($product_id);
da eroare daca vrei sa stergi un produs din admin "Call to an undefined...."

**Comment by degwebsolutions** [comment]
O sa il sterg eu astazi, mersi!

**Comment by degwebsolutions** [comment]
O sa fie sters la urmatorul update.

**Comment by degwebsolutions** [comment]
am urcat modificarea ;)
