### ISSUE TITLE
lipsa fisier admin 

### ISSUE THREAD

**Issue by cozmoximo** [opencartromania/oc-1.5.6.4-stable#2]
Salut, vezi ca s.a sters din greseala pickup.tpl din admin/view/template/shipping/
de instalat se poate instala dar cand dai edit da eroare missing tpl file

**Comment by degwebsolutions** [comment]
Ok, o sa il urc imediat ce termin de curatat si alte fisiere care sunt in asteptare. Revin cu update zilele astea.

**Comment by degwebsolutions** [comment]
fisierul a fost urcat
