### ISSUE TITLE
delete order admin error

### ISSUE THREAD

**Issue by cozmoximo** [opencartromania/oc-1.5.6.4-stable#3]
Cand incerc sa sterg o comanda imi da eroarea aceasta

Fatal error: Call to a member function deleteOrder() on a non-object in C:\localweb\websites\media2016\vqmod\vqcache\vq2-admin_controller_sale_order.php on line 164

Aceasta e linia care trebuie stearsa din admin/controller/sale/order.php la linia 137
$this->openbay->deleteOrder($order_id);

**Comment by degwebsolutions** [comment]
Mersi, sunt mai multe linii de cod ce apartin de OpenBay, vad cum imi fac timp si le scot pe toate. Apreciez si iti multumesc pentru implicare si scouting de erori :+1:

**Comment by degwebsolutions** [comment]
A fost scos
