### ISSUE TITLE
eroare editare produs

### ISSUE THREAD

**Issue by cozmoximo** [opencartromania/oc-1.5.6.4-stable#4]
de sters codul de mai jos din admin/view/template/catalog/product_form.tpl

<?php if (isset($this->request->get['product_id'])) { ?>
    function openbayLinkStatus(){
        var product_id = '<?php echo $this->request->get['product_id']; ?>';
        $.ajax({
            type: 'GET',
            url: 'index.php?route=extension/openbay/linkStatus&token=<?php echo $token; ?>&product_id='+product_id,
            dataType: 'html',
            success: function(data) {
                //add the button to nav
                $('<a href="#tab-openbay"><?php echo $tab_marketplace_links ?></a>').hide().appendTo("#tabs").fadeIn(1000);
                $('#tab-general').before(data);
                $('#tabs a').tabs();
            },
            failure: function(){

```
        },
        error: function() {

        }
    });
}

$(document).ready(function(){
    openbayLinkStatus();
});
```

<?php } ?>

//--></script>

**Comment by degwebsolutions** [comment]
La fel ca si in issue #3 revin cu un update major, sper cat de curand.
